schema_version = 1

[targets]
"aarch64-unknown-linux-gnu" = [{ selector = { kind = "direct" }, package = "wg-basic", binary = "wg-basic" }]
"x86_64-unknown-linux-gnu" = [{ selector = { kind = "direct" }, package = "wg-basic", binary = "wg-basic" }]
